import localFont from "next/font/local";
import "./globals.css";
import ThemeRegistry from "./ThemeRegistry";
import ReduxProvider from "./redux/reduxProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "boilerplate",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ReduxProvider>
          <ThemeRegistry options={{ key: "mui" }}>{children}</ThemeRegistry>
        </ReduxProvider>
      </body>
    </html>
  );
}
