import localFont from "next/font/local";
import "./globals.css";
import ThemeRegistry from "./ThemeRegistry";
import "../fonts.css";
import ReduxProvider from "./store/reduxProvider";

const Raleway = localFont({
  src: "./fonts/Raleway-Bold.ttf",
  variable: "--ralway-bold",
  weight: "100 900",
});

export const metadata = {
  title: "boilerplate",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${Raleway.variable}`}>
        <ReduxProvider>
          <ThemeRegistry options={{ key: "mui" }}>{children}</ThemeRegistry>
        </ReduxProvider>
      </body>
    </html>
  );
}
